##Credit
credit_attributes = ['credit_bal_1stmtgcredit_60dpd',
'credit_bal_agencyfirstmtg_60dpd',
'credit_bal_heloc_60dpd',
'credit_bal_nonagnfirstmtg_60dpd',
'credit_bal_nonmtgcredit_60dpd',
'credit_bal_studentloan_60dpd',
'credit_bal_totalallcredit_60dpd',
'credit_bal_autobank',
'credit_bal_autofinance',
'credit_bal_consumerfinance',
'credit_num_collections',
'credit_minmob_mtgcredit',
'credit_num_new_accounts']


pharmacy_attributes = ['rx_gpi2_42_ind',
 'rx_gpi2_90_ind',
 'rx_gpi2_46_ind',
 'rx_gpi2_82_ind',
 'rx_gpi2_57_ind',
 'rx_gpi2_34_ind',
 'rx_gpi2_04_ind',
 'rx_gpi2_62_ind',
 'rx_gpi2_83_ind',
 'rx_gpi2_01_ind',
 'rx_gpi2_16_ind',
 'rx_gpi2_66_ind',
 'rx_gpi2_68_ind',
 'rx_gpi2_72_ind',
 'rx_gpi2_24_pmpm_ct',
 'rx_gpi2_04_pmpm_ct',
 'kidney_sum',
 'rx_gpi2_68_pmpm_ct',
 'rx_gpi2_01_pmpm_ct',
 'rx_otc_pmpm_ct',
 'rx_gpi2_88_pmpm_ct',
 'rx_gpi2_75_pmpm_ct',
 'rx_gpi2_86_pmpm_ct',
 'rx_gpi2_37_pmpm_ct',
 'rx_gpi2_34_pmpm_ct',
 'rx_gpi2_02_pmpm_ct',
 'rx_gpi2_58_pmpm_ct',
 'resp_sum',
 'rx_gpi2_60_pmpm_ct',
 'rx_gpi2_61_pmpm_ct',
 'rx_gpi2_65_pmpm_ct',
 'rx_gpi2_43_pmpm_ct']